Vector Operations: In linear algerba vectors are columns

In [1]:
import numpy as np

In [3]:
u = np.array([2, 4, 5, 6])
u

array([2, 4, 5, 6])

In [4]:
v = np.array([1, 0, 0, 2])
v

array([1, 0, 0, 2])

In [6]:
u + v # element wise addition

array([3, 4, 5, 8])

In [9]:
u * v # element wise multiplication

array([ 2,  0,  0, 12])

Vector-Vector Multiplication (dot product) -> multiply each element of the array and then sum it up

In [15]:
u.shape

(4,)

In [17]:
u.shape[0]

4

In [18]:
def vector_vector_multiplication(u, v):
    assert u.shape[0] == v.shape[0]
    n = u.shape[0]
    result = 0.0
    for i in range(n):
        result = result + u[i] * v[i]
    return result

In [19]:
vector_vector_multiplication(u, v)

np.float64(14.0)

In [20]:
u.dot(v) # numpy way

np.int64(14)

Matrix-vector Multiplication -> each row of U gets multiplied by v and number of columns in U should match element of v

In [21]:
U = np.array([
    [2, 4, 5, 6],
    [1, 2, 1, 2],
    [3, 1, 2, 1]
])

In [29]:
U.shape[1] # column shape or size

4

In [24]:
def matrix_vector_multiplication(U, v):
    assert U.shape[1] == v.shape[0]
    num_rows = U.shape[0]
    result = np.zeros(num_rows)
    for i in range(num_rows):
        result[i] = vector_vector_multiplication(U[i], v)
    return result

In [25]:
matrix_vector_multiplication(U, v)

array([14.,  5.,  5.])

In [26]:
U.dot(v) # numpy way

array([14,  5,  5])

Matrix-Matrix Multiplication

In [22]:
V = np.array([
    [1, 1, 2],
    [0, 0.5, 1],
    [0, 2, 1],
    [2, 1, 0]
])

In [33]:
def matrix_matrix_multiplication(U, V):
    assert U.shape[1] == V.shape[0]
    num_rows = U.shape[0]
    num_cols = V.shape[1]
    result = np.zeros((num_rows, num_cols))
    for i in range(num_cols):
        vi = V[:, 1]
        Uvi = matrix_vector_multiplication(U, vi)
        result[:, i] = Uvi
    return result

In [34]:
matrix_matrix_multiplication(U, V)

array([[20. , 20. , 20. ],
       [ 6. ,  6. ,  6. ],
       [ 8.5,  8.5,  8.5]])

In [36]:
U.dot(V) # numpy way

array([[14. , 20. , 13. ],
       [ 5. ,  6. ,  5. ],
       [ 5. ,  8.5,  9. ]])

Identity Matrix

In [42]:
I = np.eye(3) # diagonally all elements are 1
I

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [43]:
V.dot(I)

array([[1. , 1. , 2. ],
       [0. , 0.5, 1. ],
       [0. , 2. , 1. ],
       [2. , 1. , 0. ]])

Inverse

In [45]:
Vs = V[[0, 1, 2]]
Vs

array([[1. , 1. , 2. ],
       [0. , 0.5, 1. ],
       [0. , 2. , 1. ]])

In [46]:
Vs_inv = np.linalg.inv(Vs)
Vs_inv

array([[ 1.        , -2.        ,  0.        ],
       [ 0.        , -0.66666667,  0.66666667],
       [ 0.        ,  1.33333333, -0.33333333]])

In [47]:
Vs_inv.dot(Vs)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])