One Dimentional Array

In [ ]:
import numpy as np

In [2]:
np

<module 'numpy' from '/home/codespace/.local/lib/python3.12/site-packages/numpy/__init__.py'>

In [4]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [5]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [6]:
np.full(10, 2.5)

array([2.5, 2.5, 2.5, 2.5, 2.5, 2.5, 2.5, 2.5, 2.5, 2.5])

In [10]:
a = np.array([1, 2, 3, 5, 7, 12])
a

array([ 1,  2,  3,  5,  7, 12])

In [11]:
a[2]

np.int64(3)

In [13]:
a[3] = 10
a

array([ 1,  2,  3, 10,  7, 12])

In [14]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [15]:
np.arange(3, 10)

array([3, 4, 5, 6, 7, 8, 9])

In [17]:
np.linspace(0, 1, 20)

array([0.        , 0.05263158, 0.10526316, 0.15789474, 0.21052632,
       0.26315789, 0.31578947, 0.36842105, 0.42105263, 0.47368421,
       0.52631579, 0.57894737, 0.63157895, 0.68421053, 0.73684211,
       0.78947368, 0.84210526, 0.89473684, 0.94736842, 1.        ])

Multi-dimentional Array

In [18]:
np.zeros((5, 2))

array([[0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.]])

In [20]:
n = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])

In [21]:
n[0, 1]

np.int64(2)

In [22]:
n[0, 2] = 20
n

array([[ 1,  2, 20],
       [ 4,  5,  6],
       [ 7,  8,  9]])

In [23]:
n[0] # access full raw

array([ 1,  2, 20])

In [25]:
n[2] = [10, 11, 12]
n

array([[ 1,  2, 20],
       [ 4,  5,  6],
       [10, 11, 12]])

In [33]:
n[:, 1] # access entire column 

array([ 8,  8, 11])

In [29]:
n[:, 2] = [24, 8, 16]
n

array([[24,  8, 24],
       [24,  8,  8],
       [10, 11, 16]])

Randomly Generate Arrays

In [30]:
np.random.rand(5)

array([0.97540709, 0.1926752 , 0.01279117, 0.41467829, 0.65272519])

In [38]:
np.random.rand(5, 2) # numbers between 0 and 1

array([[0.84656149, 0.07964548],
       [0.50524609, 0.0652865 ],
       [0.42812233, 0.09653092],
       [0.12715997, 0.59674531],
       [0.226012  , 0.10694568]])

In [40]:
np.random.seed(2)     # this will always generate same random numbers
np.random.rand(4, 2)

array([[0.4359949 , 0.02592623],
       [0.54966248, 0.43532239],
       [0.4203678 , 0.33033482],
       [0.20464863, 0.61927097]])

In [41]:
np.random.seed(2)     # this will always generate same random numbers
np.random.randn(4, 2) # randn for normal distribution

array([[-0.41675785, -0.05626683],
       [-2.1361961 ,  1.64027081],
       [-1.79343559, -0.84174737],
       [ 0.50288142, -1.24528809]])

In [45]:
np.random.seed(2)     # this will always generate same random numbers
100 * np.random.rand(4, 2)  # multiply each number by 100

array([[43.59949021,  2.59262318],
       [54.96624779, 43.53223926],
       [42.03678021, 33.0334821 ],
       [20.4648634 , 61.92709664]])

In [47]:
np.random.seed(2)
np.random.randint(low=0, high=100, size=(5, 2)) # generate number between provided integer range

array([[40, 15],
       [72, 22],
       [43, 82],
       [75,  7],
       [34, 49]])

Element-wise Operations

In [53]:
a = np.arange(1, 6)
a

array([1, 2, 3, 4, 5])

In [54]:
a + 1  # add number to each element

array([2, 3, 4, 5, 6])

In [55]:
a * 2 # multiply each element by 2 and similarly we can divide, subtract

array([ 2,  4,  6,  8, 10])

In [59]:
b = (10 + (a * 2)) ** 2 / 100
b

array([1.44, 1.96, 2.56, 3.24, 4.  ])

In [61]:
a + b # similarly we can subtract, multiply, divide 

array([2.44, 3.96, 5.56, 7.24, 9.  ])

Comparison Operations

In [62]:
a

array([1, 2, 3, 4, 5])

In [63]:
a >= 2

array([False,  True,  True,  True,  True])

In [64]:
b

array([1.44, 1.96, 2.56, 3.24, 4.  ])

In [65]:
a > b

array([False,  True,  True,  True,  True])

In [67]:
a[a > b] # which elements of array a is greater than b

array([2, 3, 4, 5])

Summarizing Operations

In [68]:
a.min()

np.int64(1)

In [69]:
a.max()

np.int64(5)

In [70]:
a.sum()

np.int64(15)

In [72]:
a.std() # standard deviation

np.float64(1.4142135623730951)